const path = require('path');
const express=require('express');
const bodyParser = require('body-parser');
const app=express();
app.set('view engine', 'ejs');
app.set('views', 'views');
const ide_route=require('./route/ide');
app.use(bodyParser.urlencoded({ extended: false }));
app.use(express.static(path.join(__dirname, 'static')));
app.use(ide_route);
app.listen(4000);